keep-alive:
  url: ${RENDER_EXTERNAL_URL:https://localhost:8080}
server:
  port: ${PORT:8080}
spring:
  application:
    name: garmin-connect-weight-api
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true