server:
  port: ${PORT:8080}
spring:
  application:
    name: garmin-connect-weight-api
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true
keep-alive: ${RENDER_EXTERNAL_HOSTNAME:https://localhost:8080}